### ISSUE TITLE
To start the already installed kubernetes cluster

### ISSUE THREAD

**Issue by aadhik** [linuxkit/kubernetes#41] opened 2018-01-06 14:18 UTC
**Description**

**Steps to reproduce the issue:**
1) Forcefully power down the host machine

**Describe the results you received:**
Kubernetes cluster does not start.
To start , have to clear all the state directories, which in essence creates new cluster and all changes are lost

**Describe the results you expected:**
How to start the stopped cluster. If you could tell me how , can setit up as init script

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ijc** [comment] 2018-01-08 12:39
I suspect this is just another manifestation of #26.

If it isn't then it would seem most likely to be due to corruption of the VM disk caused by the graceless shutdown of the host, which is likely to be influenced by the configuration used for the virtual disk.

**Comment by ijc** [comment] 2018-02-14 16:17
Closing as dup of #26

**Closed by ijc** 2018-02-14 16:17 UTC
